jwt:
  issuer: hojooglim@gmail.com
  secret_key: Project

spring:
  data:
    redis:
      port: 6379
      host: localhost

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 991013114702-onqp7vli1s3jhej98vfvcqmp8kjm2gdd.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            client-id: 8rMRGOBFggad21EPNAoS
            client-secret: txl3lJooF8
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
          kakao:
            clientId: b51a87369fa2be0b6083d66f1c49470e
            clientSecret: 67vWfW0TplCBct9VVCW5YwSnhIzIFsOF
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
            clientName: Kakao
          # Provider 설정
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id